#!/usr/bin/env node

/**
 * Git Guardian — Hook Installer
 * ═════════════════════════════
 * Learner AI Trading System
 *
 * Cross-platform installer that creates Git hooks pointing to
 * the guardian scripts. Runs automatically via `npm install` (prepare script).
 *
 * Creates:
 *   .git/hooks/pre-commit  → runs scripts/git-guardian.js
 *   .git/hooks/commit-msg  → runs scripts/commit-msg-validator.js
 */

const fs = require('fs');
const path = require('path');

// ─── ANSI Colors ──────────────────────────────────────────────
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const CYAN = '\x1b[36m';
const BOLD = '\x1b[1m';
const DIM = '\x1b[2m';
const RESET = '\x1b[0m';

// ─── Paths ────────────────────────────────────────────────────
const ROOT = path.join(__dirname, '..');
const GIT_DIR = path.join(ROOT, '.git');
const HOOKS_DIR = path.join(GIT_DIR, 'hooks');

// ─── Hook Definitions ────────────────────────────────────────
const HOOKS = [
    {
        name: 'pre-commit',
        script: 'scripts/git-guardian.js',
        description: 'Git Guardian — 3-Gate Pre-Commit Validation',
    },
    {
        name: 'commit-msg',
        script: 'scripts/commit-msg-validator.js',
        description: 'Git Guardian — Commit Message Validator',
    },
];

function generateHookScript(hook) {
    const isWindows = process.platform === 'win32';

    if (isWindows) {
        // Windows: Use node directly (Git for Windows runs sh hooks via MINGW)
        // The hook script must be a shell script even on Windows (Git uses MINGW sh)
        return [
            '#!/bin/sh',
            `# ${hook.description}`,
            '# Auto-generated by scripts/install-hooks.js — do not edit',
            '',
            `# Resolve the script path relative to the repo root`,
            `SCRIPT_PATH="$(git rev-parse --show-toplevel)/${hook.script}"`,
            '',
            '# Run the guardian script with node',
            `exec node "$SCRIPT_PATH" "$@"`,
            '',
        ].join('\n');
    }

    // Unix: Standard shell hook
    return [
        '#!/bin/sh',
        `# ${hook.description}`,
        '# Auto-generated by scripts/install-hooks.js — do not edit',
        '',
        `SCRIPT_PATH="$(git rev-parse --show-toplevel)/${hook.script}"`,
        '',
        `exec node "$SCRIPT_PATH" "$@"`,
        '',
    ].join('\n');
}

function installHooks() {
    console.log(`\n${CYAN}╔══════════════════════════════════════════════╗${RESET}`);
    console.log(`${CYAN}║  🛡️  Git Guardian — Hook Installer           ║${RESET}`);
    console.log(`${CYAN}╚══════════════════════════════════════════════╝${RESET}\n`);

    // Check for .git directory
    if (!fs.existsSync(GIT_DIR)) {
        console.log(`${YELLOW}⚠️  No .git directory found — skipping hook installation${RESET}`);
        console.log(`${DIM}   Run 'git init' first, then 'node scripts/install-hooks.js'${RESET}\n`);
        process.exit(0);
    }

    // Create hooks directory if it doesn't exist
    if (!fs.existsSync(HOOKS_DIR)) {
        fs.mkdirSync(HOOKS_DIR, { recursive: true });
        console.log(`${DIM}Created ${HOOKS_DIR}${RESET}\n`);
    }

    let installed = 0;
    let skipped = 0;

    for (const hook of HOOKS) {
        const hookPath = path.join(HOOKS_DIR, hook.name);
        const scriptFullPath = path.join(ROOT, hook.script);

        // Verify the source script exists
        if (!fs.existsSync(scriptFullPath)) {
            console.log(`${YELLOW}⚠️  Script not found: ${hook.script} — skipping ${hook.name}${RESET}`);
            skipped++;
            continue;
        }

        // Check if hook already exists and is ours
        if (fs.existsSync(hookPath)) {
            const existing = fs.readFileSync(hookPath, 'utf8');
            if (existing.includes('Git Guardian') && existing.includes(hook.script)) {
                console.log(`${DIM}  ○ ${hook.name} — already installed (up to date)${RESET}`);
                skipped++;
                continue;
            }

            // Backup existing hook if it's not ours
            const backupPath = hookPath + '.backup';
            fs.renameSync(hookPath, backupPath);
            console.log(`${YELLOW}  ⚠ Backed up existing ${hook.name} → ${hook.name}.backup${RESET}`);
        }

        // Write the hook
        const hookContent = generateHookScript(hook);
        fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });

        // On Windows, also try to ensure the file is executable via Git
        try {
            if (process.platform !== 'win32') {
                fs.chmodSync(hookPath, 0o755);
            }
        } catch {
            // chmod may fail on Windows, that's OK
        }

        console.log(`${GREEN}  ✓ ${hook.name} → ${hook.script}${RESET}`);
        console.log(`${DIM}    ${hook.description}${RESET}`);
        installed++;
    }

    // Summary
    console.log(`\n${CYAN}──────────────────────────────────────────────${RESET}`);
    if (installed > 0) {
        console.log(`${GREEN}${BOLD}✅ ${installed} hook(s) installed successfully${RESET}`);
    }
    if (skipped > 0) {
        console.log(`${DIM}   ${skipped} hook(s) already up to date${RESET}`);
    }
    console.log(`${DIM}   Hooks directory: ${HOOKS_DIR}${RESET}\n`);
}

installHooks();
